<?php
/*
 *
 * Version: 0.0.1
 * License: GPLv2
 * Text Domain: plugin_test
 * Author URI: #
 * Author: Miguel Pinto
 * Plugin Name: Plugin Test
 * Description: description
 * Plugin URI: #
 * Domain Path: /languages/
 *
 *
 * Paste your plugin license information here - for more info about the GPLv2 license please check the link bellow
 * - https://developer.wordpress.org/plugins/the-basics/including-a-software-license
 *
 *
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

define("PLUGIN_TEST_BASE_PATH", plugin_dir_path( __FILE__ ));
define("PLUGIN_TEST_INC_PATH", plugin_dir_path( __FILE__ ) . "/inc");
define("PLUGIN_TEST_JS_URL", plugin_dir_url( __FILE__ ) . "/res/js");
define("PLUGIN_TEST_STYLES_URL", plugin_dir_url( __FILE__ ) . "/res/css");
define("PLUGIN_TEST_TEMPLATES_PATH", plugin_dir_path( __FILE__ ) . "/templates");

function init_plugin_test_plugin ()
{

}
add_action("init", "init_plugin_test_plugin");

function activate_plugin_test_plugin ()
{

}
register_activation_hook(__FILE__, "activate_plugin_test_plugin");

/*
 *
 * File generated by WPTERMINAL - feel free to colaborate at https://github.com/jmlp-131092/wpterminal
 *
 */

?>
